language: python
python:
  - 3.5
install:
  - pip install coveralls
before_script:
  - git clone https://github.com/AaronKel/custom-micropython.git
  - cd custom-micropython
  - ./micropython -m upip install micropython-unittest
  - cp ./micropython ../
  - cd ../
script:
  - ./micropython -m TestSuite
  - coverage run  TestSuite.py
after_success:
  - coveralls
